### ISSUE TITLE
还维护吗？

### ISSUE THREAD

**Issue by JakeWoki** [ViTess/RxBus#2]
sticky事件等希望支持

**Comment by JakeWoki** [comment]
event事件有时候总是没收到

**Comment by ViTess** [comment]
方便提供一下使用场景、tag和方法参数？有没有出现什么打印？

**Comment by JakeWoki** [comment]
在service中发出event，在Presenter（MVP的P）中接收，有时全部没收到，重新运行一次又正常，没看到日志，没设置tag

**Comment by ViTess** [comment]
重新运行是指关掉应用重新打开还是用IDE重新运行？如果时Android studio的话有否打开Install run?

**Comment by JakeWoki** [comment]
run，重新打开没试过，返回前一个界面再进入也不行，没用Install run

**Comment by ViTess** [comment]
这个看起来好像没有成功生成对应的Proxy文件
你试下在运行时没有接收到事件时，查看RxBus里的PROXY_CACHE，有没有获取到调用RxBus.register的所在类的proxy

**Comment by JakeWoki** [comment]
等下遇到再看下

**Comment by JakeWoki** [comment]
sticky事件等还更新不？

**Comment by ViTess** [comment]
会更新，但是最近在忙工作上的事情，近期不会加

**Comment by JakeWoki** [comment]
连续发两个不同event，有时收到两个，有时只收到一个，收到一个时BusSubscriber的onNext抛出异常：
A event cannot be cast to B event
PROXY_CACHE有两个值，SUBJECTS只有一个。
看了下源码，所有注册都会发送并接收，匹配由rxjava来匹配，异常是rxjava抛出的，实际原因是SUBJECTS丢失了一个。（匹配由rxjava来匹配感觉不是很好啊）

**Comment by JakeWoki** [comment]
![20170515150057](https://cloud.githubusercontent.com/assets/6948411/26046737/fc6c2400-3982-11e7-9ba2-36c7eb8c7bfa.png)
![20170515150134](https://cloud.githubusercontent.com/assets/6948411/26046879/92c58e14-3983-11e7-8738-3ac941a24290.png)
全部事件没收到有PROXY_CACHE，但是SUBJECTS只有一个，这个不对吧

**Comment by JakeWoki** [comment]
应该是rxjava抛出异常后不再执行其它event了，相当于只发了一个

**Comment by ViTess** [comment]
在rxjava里匹配参数属于无奈之举，之前没有什么好办法可以解决这个参数类型自匹配的问题，看看之后能不能想到更好的办法替代。
感谢你提供的信息，我会测试进行修改的。

**Comment by ViTess** [comment]
@JakeWoki try to use dev branch or use 2.0.2-SNAPSHOT

**Comment by JakeWoki** [comment]
还没提交吗？没看到有改动的地方

**Comment by ViTess** [comment]
snapshot提交在dev分支上，配置maven为https://oss.sonatype.org/content/repositories/snapshots/ 也可以获取2.0.2-SNAPSHOT版本
